apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: java-app-backend-jwt-secret
  namespace: ui7
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: deepagentdevops-dev/ui7/JWT_SECRET
